apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaskapp-v1
  name: flaskapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp-v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaskapp-v1
    spec:
      containers:
      - image: alexmavcouk/blog-app-demo:20230912211935
        name: blogapp
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
        - name: HONEYCOMB_API_KEY
          valueFrom:
            secretKeyRef:
              name: honeycombio-api
              key: HONEYCOMB_API_KEY
        - name: HONEYCOMB_METRICS_DATASET
          valueFrom: 
            configMapKeyRef:
              key: HONEYCOMB_METRICS_DATASET
              name: honeycombio-cm
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              key: OTEL_EXPORTER_OTLP_ENDPOINT
              name: honeycombio-cm
        - name: OTEL_SERVICE_NAME
          valueFrom: 
            configMapKeyRef:
              key: OTEL_SERVICE_NAME
              name: honeycombio-cm
        resources: {}
status: {}